language: objective-c
compiler: clang
env:
  global:
    secure: LBTN8d1hS7ocrqDwxLQqU0tfK3FMCXBI8q1yASEjtkp/v5HEyFkbj22H4jXZ20SkpCTlIG2L6i/fU3d6KzJUzTFuxkQEWsnjkj4jAhxGEWRsT1RV6VcUPQDGLHapXwTy+ZYgMNxE7aAdQaBskPHdVzAhjrzlTwVuKp6KjFn+kMU=
  matrix:
  - NAME="osx" \ SCRIPT_PATH="scripts/$NAME" \ SCRIPT="$SCRIPT_PATH/buildPG.sh"
script: "$SCRIPT"
git:
  depth: 10
before_install:
- openssl aes-256-cbc -K $encrypted_cd38768cbb9d_key -iv $encrypted_cd38768cbb9d_iv
  -in id_rsa.enc -out id_rsa -d
